---
 - name: APP
   hosts: localhost
   become: true
   tasks:
   - name: Clone a github repository
     git:
       repo: https://github.com/qyjohn/simple-lamp
       dest: /var/www/html/simple-lamp
       clone: yes
       update: yes
       force: yes

     notify:
       - Restart Apache
   handlers:
    - name: Restart Apache
      service:
        name: apache2
        state: restarted
