---
- name: upgrade all pkg
  hosts: localhost
  become: true
  vars:
    - vars/default.yml
  tasks:
    - name: apt upgrade all
      apt: 
        name: '*'
        state: latest

    - name: Install prerequisites
      apt: name={{ item }} update_cache=yes state=latest force_apt_get=yes
      loop: [ 'aptitude' ]

  # Install LAMP 
    - name: Install LAMP
      apt: name={{ item }} update_cache=yes state=latest
      loop: [ 'apache2', 'mysql-server', 'python3-pymysql', 'php', 'php-mysql', 'libapache2-mod-php' ]

    - name: Create document root
      file:
        path: "/var/www/{{ http_host }}"
        state: directory
        owner: "{{ app_user }}"
        mode: '0755'

  # MySQL
    - name: start and enable mysql service
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Sets the root password
      become: true
      no_log: true
      mysql_user:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        name: root
        password: "{{ mysql_root_password }}"
        check_implicit_admin: true
        login_unix_socket: /var/run/mysqld/mysqld.sock

  # Install memcached 
    - include_tasks: memcached.yml

  # Install simpl-lamp-app
    - iclude_tasks: app.yml

  # Configuration UFW 
    - name: "UFW - Allow HTTP on port {{ http_port }}"
      ufw:
        rule: allow
        port: "{{ http_port }}"
        proto: tcp


  #Apache

    - name: Set up Apache virtualhost
      template:
        src: "templates/apache.conf.j2"
        dest: "/etc/apache2/sites-available/{{ http_conf }}"
      notify: Reload Apache

    - name: Set up config.php
      ansible.builtin.template:
        src: "templates/config.php.j2"
        dest: "/var/www/{{ http_host }}/conf.php"

    - name: Enable new site
      shell: /usr/sbin/a2ensite {{ http_conf }}
      notify: Reload Apache

    - name: Disable default Apache site
      shell: /usr/sbin/a2dissite 000-default.conf
      when: disable_default
      notify: Reload Apache

    - name: Change directory owner
      become: true
      ansible.builtin.file:
        state: directory
        path: /var/www/{{ http_host }}/uploads
        owner: www-data
        group: www-data

  # PHP Index Page
    - name: Sets Up PHP Info Page
      template:
        src: "templates/index.php.j2"
        dest: "/var/www/{{ http_host }}/index.php"
